// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// prisma.config.ts é a configuração do banco de dados
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

dotenv.config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"], // puxa do .env — igual ao nosso dotenv
  },
});
